name: capstone
channels:
  - conda-forge
  - plotly
dependencies:
  - python==3.9.13
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - openai==0.23.0
  - plotly==5.10.0
  - boto3==1.24.80
  # Interactive
  - ipykernel==6.15.2
  - matplotlib==3.5.3
  - seaborn==0.12.0
  # Testing
  - pycodestyle==2.9.1
  - pytest==7.1.3
  - pytest-cov==3.0.0
  - pytest-pycodestyle==2.2.0
  # Pip
  - pip==22.2.2