name: capstone
channels:
  - conda-forge
  - plotly
  - pytorch
dependencies:
  - python==3.9.13
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - openai==0.23.0
  - plotly==5.10.0
  - boto3==1.24.80
  - nltk==3.6.7
  - pytorch==1.13.0
  - torchvision==0.2.2
  - torchaudio==0.13.0
  - cuda==11.7.1
  - transformers==4.24.0
  # Interactive
  - jupyter
  - matplotlib==3.5.3
  - seaborn==0.12.0
  # Testing
  - pycodestyle==2.9.1
  - pytest==7.1.3
  - pytest-cov==3.0.0
  - pytest-pycodestyle==2.2.0
  # Pip
  - pip==22.2.2
  - pip:
    - xgboost
