DATA_DIR = "data"
MODEL_DIR = "model"
REPORTS_DIR = "reports"
SAVED_MODELS = "saved_models"

XLSX_DATA = "Regulatory Requirements.xlsx"
XLSX_SHEET = "Requirements List"

TEXT = "Text"
TARGET = "Standard mapping?"
ORIGINAL_TEXT = "Original Text"
IS_MAPPED = "Mapped to a standard?"
IS_MAPPED_TRUE = "Mapped to a standard"
SPLIT = "Split"
DEVELOP = "Development"
TEST = "Test"

HAMMING_LOSS = "Hamming Loss"
ACCURACY = "Accuracy"
PRECISION = "Precision"
RECALL = "Recall"
F1_SCORE = "F1 Score"
F2_SCORE = "F2 Score"

PREDICTION = "prediction"
CORRECTED = "corrected_prediction"
